import {
  int,
  mysqlEnum,
  mysqlTable,
  text,
  timestamp,
  varchar,
  json,
  decimal,
  boolean,
  index,
} from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Goals — user's high-level business objectives
 */
export const goals = mysqlTable("goals", {
  id: int("id").autoincrement().primaryKey(),
  goalText: text("goalText").notNull(),
  status: mysqlEnum("status", ["active", "paused", "completed", "archived"]).default("active").notNull(),
  subGoals: json("subGoals"),
  priority: int("priority").default(5).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Goal = typeof goals.$inferSelect;
export type InsertGoal = typeof goals.$inferInsert;

/**
 * Task Queue — priority queue of tasks generated by the autonomous system
 */
export const taskQueue = mysqlTable("task_queue", {
  id: int("id").autoincrement().primaryKey(),
  goalId: int("goalId"),
  source: varchar("source", { length: 64 }).default("task_generator").notNull(),
  description: text("description").notNull(),
  priorityScore: int("priorityScore").default(50).notNull(),
  status: mysqlEnum("status", ["pending", "in_progress", "completed", "failed", "cancelled", "awaiting_approval"]).default("pending").notNull(),
  assignedAgent: varchar("assignedAgent", { length: 64 }).default("autonomous_worker"),
  actionType: varchar("actionType", { length: 64 }),
  actionPayload: json("actionPayload"),
  resultSummary: text("resultSummary"),
  metadata: json("metadata"),
  estimatedValue: decimal("estimatedValue", { precision: 10, scale: 2 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  completedAt: timestamp("completedAt"),
}, table => [
  index("task_source_created_idx").on(table.source, table.createdAt),
  index("task_status_completed_idx").on(table.status, table.completedAt),
]);

export type Task = typeof taskQueue.$inferSelect;
export type InsertTask = typeof taskQueue.$inferInsert;

/**
 * Execution Log — every action taken by the system
 */
export const executionLog = mysqlTable("execution_log", {
  id: int("id").autoincrement().primaryKey(),
  taskId: int("taskId"),
  actionType: varchar("actionType", { length: 64 }).notNull(),
  details: json("details"),
  outcome: mysqlEnum("outcome", ["success", "failure", "partial", "pending"]).default("pending").notNull(),
  errorMessage: text("errorMessage"),
  durationMs: int("durationMs"),
  tokensCost: int("tokensCost"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
}, table => [
  index("execution_outcome_created_task_idx").on(
    table.outcome,
    table.createdAt,
    table.taskId
  ),
]);

export type ExecutionLogEntry = typeof executionLog.$inferSelect;
export type InsertExecutionLogEntry = typeof executionLog.$inferInsert;

/**
 * Evaluations — success/failure metrics for completed tasks
 */
export const evaluations = mysqlTable("evaluations", {
  id: int("id").autoincrement().primaryKey(),
  taskId: int("taskId"),
  success: mysqlEnum("success", ["true", "false", "partial"]).notNull(),
  conversionRate: decimal("conversionRate", { precision: 5, scale: 4 }),
  costTokens: int("costTokens"),
  lessonLearned: text("lessonLearned"),
  strategyUsed: varchar("strategyUsed", { length: 128 }),
  improvementSuggestion: text("improvementSuggestion"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Evaluation = typeof evaluations.$inferSelect;
export type InsertEvaluation = typeof evaluations.$inferInsert;

/**
 * Opportunities — detected market opportunities
 */
export const opportunities = mysqlTable("opportunities", {
  id: int("id").autoincrement().primaryKey(),
  source: varchar("source", { length: 128 }).notNull(),
  description: text("description").notNull(),
  priority: mysqlEnum("priority", ["low", "medium", "high", "critical"]).default("medium").notNull(),
  status: mysqlEnum("status", ["new", "investigating", "actioned", "dismissed"]).default("new").notNull(),
  estimatedValue: decimal("estimatedValue", { precision: 10, scale: 2 }),
  metadata: json("metadata"),
  detectedAt: timestamp("detectedAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Opportunity = typeof opportunities.$inferSelect;
export type InsertOpportunity = typeof opportunities.$inferInsert;

/**
 * System Config — settings, limits, safety controls
 */
export const systemConfig = mysqlTable("system_config", {
  id: int("id").autoincrement().primaryKey(),
  key: varchar("configKey", { length: 128 }).notNull().unique(),
  value: text("configValue").notNull(),
  description: text("description"),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type SystemConfigEntry = typeof systemConfig.$inferSelect;
export type InsertSystemConfigEntry = typeof systemConfig.$inferInsert;

/**
 * Daily Metrics — aggregated daily stats
 */
export const dailyMetrics = mysqlTable("daily_metrics", {
  id: int("id").autoincrement().primaryKey(),
  date: varchar("date", { length: 10 }).notNull(),
  tasksGenerated: int("tasksGenerated").default(0).notNull(),
  tasksCompleted: int("tasksCompleted").default(0).notNull(),
  tasksFailed: int("tasksFailed").default(0).notNull(),
  callsMade: int("callsMade").default(0).notNull(),
  emailsSent: int("emailsSent").default(0).notNull(),
  smsSent: int("smsSent").default(0).notNull(),
  apiSpendCents: int("apiSpendCents").default(0).notNull(),
  successRate: decimal("successRate", { precision: 5, scale: 4 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type DailyMetric = typeof dailyMetrics.$inferSelect;
export type InsertDailyMetric = typeof dailyMetrics.$inferInsert;
